port: 7880
bind_addresses: ["0.0.0.0"]

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  enable_loopback_candidate: true

redis:
  address: "localhost:6379"

keys:
  "APIe5ea27b80c9f4c5": "SECRETUGicrPXBnKpGqKTwH4CH2rU9Dp7N5tW75Q7zLh"

log_level: "info"

development: true
