port: 7880
log_level: info

redis:
  address: redis:6379

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50100
  use_external_ip: false

keys:
  devkey: M1zLEZjWLAi25sLukWvQtAoCQoMLfSyC

room:
  enabled_codecs:
    - mime: audio/opus
